In [11]:
import numpy as np

In [12]:
class NeuralNetwork:
    def __init__(self):
        np.random.seed(1)
        
        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def train(self, training_inputs, training_outputs, training_iterations):
        
        for iteration in range(training_iterations):
            
            output = self.think(training_inputs)
            error = training_outputs - output
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
            self.synaptic_weights += adjustments
            
    def think(self, inputs):
        
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        
        return output

In [13]:
neural_network = NeuralNetwork()
    
print('Random synaptic weights')
neural_network.synaptic_weights

Random synaptic weights


array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [14]:
training_inputs = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
])

In [15]:
training_outputs = np.array([[0, 1, 1, 0]]).T

In [16]:
neural_network.train(training_inputs, training_outputs, 10000)

In [17]:
print('Synaptic weights after training:')
print(neural_network.synaptic_weights)

Synaptic weights after training:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [18]:
neural_network.think(np.array([0, 0, 1]))

array([0.009664])

In [19]:
neural_network.think(np.array([1, 0, 0]))

array([0.99993704])